language: python
python:
    - 3.5
services:
    - redis-server
before_install:
    - sudo apt-get -qq update

    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda

    - while read requirement; do conda install $requirement; done < requirements.txt
    - conda install scikit-learn pytables
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    ./test.sh
after_success:
    coveralls
