"""precalculated delays

Revision ID: 1a3e96d4638f
Revises: cfb08f52e367
Create Date: 2016-10-11 23:53:34.832309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3e96d4638f'
down_revision = 'cfb08f52e367'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight', sa.Column('delay_mins', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_flight_delay_mins'), 'flight', ['delay_mins'], unique=False)
    op.create_foreign_key(None, 'flight', 'airport', ['departure_airport'], ['code'])
    op.create_foreign_key(None, 'flight', 'airport', ['arrival_airport'], ['code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_constraint(None, 'flight', type_='foreignkey')
    op.drop_index(op.f('ix_flight_delay_mins'), table_name='flight')
    op.drop_column('flight', 'delay_mins')
    ### end Alembic commands ###
