"""Init.

Revision ID: 5def81573f31
Revises: 
Create Date: 2016-09-27 22:54:44.899832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5def81573f31'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=2), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=False),
    sa.Column('departure_airport', sa.String(length=3), nullable=False),
    sa.Column('arrival_airport', sa.String(length=3), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=True),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    ### end Alembic commands ###
