"""Indexes.

Revision ID: 75b00c5b47fc
Revises: 23c1e61027c7
Create Date: 2016-10-04 03:25:11.818548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b00c5b47fc'
down_revision = '23c1e61027c7'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flight_actual_departure'), 'flight', ['actual_departure'], unique=False)
    op.create_index(op.f('ix_flight_arrival_airport'), 'flight', ['arrival_airport'], unique=False)
    op.create_index(op.f('ix_flight_carrier'), 'flight', ['carrier'], unique=False)
    op.create_index(op.f('ix_flight_departure_airport'), 'flight', ['departure_airport'], unique=False)
    op.create_index(op.f('ix_flight_flight_number'), 'flight', ['flight_number'], unique=False)
    op.create_index(op.f('ix_flight_scheduled_departure'), 'flight', ['scheduled_departure'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_scheduled_departure'), table_name='flight')
    op.drop_index(op.f('ix_flight_flight_number'), table_name='flight')
    op.drop_index(op.f('ix_flight_departure_airport'), table_name='flight')
    op.drop_index(op.f('ix_flight_carrier'), table_name='flight')
    op.drop_index(op.f('ix_flight_arrival_airport'), table_name='flight')
    op.drop_index(op.f('ix_flight_actual_departure'), table_name='flight')
    ### end Alembic commands ###
