"""airline table

Revision ID: 7bedc67e9818
Revises: 1a3e96d4638f
Create Date: 2016-10-12 04:30:39.366175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bedc67e9818'
down_revision = '1a3e96d4638f'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('alias', sa.String(length=70), nullable=True),
    sa.Column('iata', sa.String(length=3), nullable=True),
    sa.Column('icao', sa.String(length=4), nullable=True),
    sa.Column('call_sign', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_call_sign'), 'carrier', ['call_sign'], unique=False)
    op.create_index(op.f('ix_carrier_iata'), 'carrier', ['iata'], unique=False)
    op.create_index(op.f('ix_carrier_icao'), 'carrier', ['icao'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carrier_icao'), table_name='carrier')
    op.drop_index(op.f('ix_carrier_iata'), table_name='carrier')
    op.drop_index(op.f('ix_carrier_call_sign'), table_name='carrier')
    op.drop_table('carrier')
    ### end Alembic commands ###
