"""Airlines table & precalculated delays column.

Revision ID: a1aaff57e2ff
Revises: cfb08f52e367
Create Date: 2016-10-13 22:14:33.643834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1aaff57e2ff'
down_revision = 'cfb08f52e367'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('alias', sa.String(length=70), nullable=True),
    sa.Column('iata', sa.String(length=3), nullable=True),
    sa.Column('icao', sa.String(length=4), nullable=True),
    sa.Column('call_sign', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_call_sign'), 'carrier', ['call_sign'], unique=False)
    op.create_index(op.f('ix_carrier_iata'), 'carrier', ['iata'], unique=False)
    op.create_index(op.f('ix_carrier_icao'), 'carrier', ['icao'], unique=True)
    op.add_column('flight', sa.Column('delay_mins', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_flight_delay_mins'), 'flight', ['delay_mins'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_delay_mins'), table_name='flight')
    op.drop_column('flight', 'delay_mins')
    op.drop_index(op.f('ix_carrier_icao'), table_name='carrier')
    op.drop_index(op.f('ix_carrier_iata'), table_name='carrier')
    op.drop_index(op.f('ix_carrier_call_sign'), table_name='carrier')
    op.drop_table('carrier')
    ### end Alembic commands ###
