"""Group index.

Revision ID: bf308cef7025
Revises: 75b00c5b47fc
Create Date: 2016-10-04 04:34:36.601653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf308cef7025'
down_revision = '75b00c5b47fc'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('flight_stop', 'flight', ['carrier', 'flight_number', 'scheduled_departure'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('flight_stop', table_name='flight')
    ### end Alembic commands ###
