"""Airports table.

Revision ID: cfb08f52e367
Revises: bf308cef7025
Create Date: 2016-10-06 02:30:06.624630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb08f52e367'
down_revision = 'bf308cef7025'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.SmallInteger(), nullable=True),
    sa.Column('tz_offset', sa.Numeric(), nullable=True),
    sa.Column('dst', sa.String(length=1), nullable=True),
    sa.Column('tz_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airport_code'), 'airport', ['code'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airport_code'), table_name='airport')
    op.drop_table('airport')
    ### end Alembic commands ###
